jobs:
  build:
    env:
      CI_BUILD_NUMBER: ${{ github.run_number }}
      CI_PULL_REQUEST: ${{ github.event.number }}
      JAVADOCS_TOKEN: ${{ secrets.JAVADOCS_TOKEN }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v2
    - continue-on-error: true
      name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - continue-on-error: true
      name: Cache Gradle packages
      uses: actions/cache@v2
      with:
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
        path: ~/.gradle/caches
        restore-keys: ${{ runner.os }}-gradle
    - continue-on-error: true
      name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - continue-on-error: true
      name: Grant execute permission for push
      run: chmod +x push.sh
    - continue-on-error: true
      name: Build with Gradle
      run: ./gradlew build javadoc --stacktrace
    - continue-on-error: true
      name: Upload to Codecov
      uses: codecov/codecov-action@v1
    - continue-on-error: true
      name: Push Javadocs
      run: ./push.sh
name: Java CI with Gradle
on:
  repository_dispatch:
    types: trigger-ga___gradle.yml
